/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package netbeans.demo;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lists.JListHelper;
import tables.FilteredTableModel;

/**
 *
 * @author Jacob
 */
public class DemoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DemoFrame
     */
    public DemoFrame() {
        initComponents();
        //FilteredTextField
        filteredTextField.setConnectedList(jList1);
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("Test item 2");
        arrayList.add("Another thing");
        arrayList.add("Yet another thing");
        arrayList.add("Unique text");
        arrayList.add("Test item 1");
        filteredTextField.setData(arrayList);
        //JListHelper
        DefaultListModel<String> defaultListModel1 = new DefaultListModel<>();
        DefaultListModel<String> defaultListModel2 = new DefaultListModel<>();
        defaultListModel1.addElement("Item 1");
        defaultListModel1.addElement("Item 2");
        defaultListModel1.addElement("Item 3");
        defaultListModel1.addElement("Item 4");
        defaultListModel1.addElement("Item 5");
        defaultListModel2.addElement("Item 6");
        defaultListModel2.addElement("Item 7");
        defaultListModel2.addElement("Item 8");
        defaultListModel2.addElement("Item 9");
        defaultListModel2.addElement("Item 10");
        jlistHelper1.setModel(defaultListModel1);
        jlistHelper2.setModel(defaultListModel2);
        JListHelper.registerLinkedJListListener(jlistHelper1, jlistHelper2);
        //FilteredTableModel
        jTable1.setModel(new FilteredTableModel(tableFilterTextField, jTable1.getModel(), 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        filteredTextFieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filteredTextField = new textfields.FilteredTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlistHelperPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistHelper1 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlistHelper2 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        filteredTablePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tableFilterTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tableFilterIndexSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("Filter:");

        filteredTextField.setMinimumSize(new java.awt.Dimension(6, 50));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Type text into the filter text field to reduce the visible options within the JList.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout filteredTextFieldPanelLayout = new javax.swing.GroupLayout(filteredTextFieldPanel);
        filteredTextFieldPanel.setLayout(filteredTextFieldPanelLayout);
        filteredTextFieldPanelLayout.setHorizontalGroup(
            filteredTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filteredTextFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(filteredTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(filteredTextFieldPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(filteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        filteredTextFieldPanelLayout.setVerticalGroup(
            filteredTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filteredTextFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filteredTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filteredTextFieldPanelLayout.createSequentialGroup()
                        .addGroup(filteredTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(filteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Filtered Text Field", filteredTextFieldPanel);

        jlistHelper1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlistHelper1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jlistHelper1);

        jlistHelper2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlistHelper2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jlistHelper2);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Click items in either JList to transfer them to the other list.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane5.setViewportView(jTextArea2);

        javax.swing.GroupLayout jlistHelperPanelLayout = new javax.swing.GroupLayout(jlistHelperPanel);
        jlistHelperPanel.setLayout(jlistHelperPanelLayout);
        jlistHelperPanelLayout.setHorizontalGroup(
            jlistHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlistHelperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlistHelperPanelLayout.setVerticalGroup(
            jlistHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlistHelperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlistHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("JList Helper", jlistHelperPanel);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"This", "is", "a", "test"},
                {"of", "the", "Java", "broadcasting"},
                {"company.", "Alpha", "Bald Eagle", "Cat"},
                {"Dog", "Epic", "Falcon", "Gamma"}
            },
            new String [] {
                "Index 0", "Index 1", "Index 2", "Index 3"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        jLabel2.setText("Filter:");

        tableFilterIndexSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        tableFilterIndexSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tableFilterIndexSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("Table index to search within:");

        javax.swing.GroupLayout filteredTablePanelLayout = new javax.swing.GroupLayout(filteredTablePanel);
        filteredTablePanel.setLayout(filteredTablePanelLayout);
        filteredTablePanelLayout.setHorizontalGroup(
            filteredTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filteredTablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(filteredTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filteredTablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tableFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filteredTablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tableFilterIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        filteredTablePanelLayout.setVerticalGroup(
            filteredTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
            .addGroup(filteredTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filteredTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tableFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(filteredTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableFilterIndexSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filtered Table", filteredTablePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableFilterIndexSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tableFilterIndexSpinnerStateChanged
        FilteredTableModel model = (FilteredTableModel) jTable1.getModel();
        model.setColumnToSearch((int) tableFilterIndexSpinner.getValue());
    }//GEN-LAST:event_tableFilterIndexSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DemoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filteredTablePanel;
    private textfields.FilteredTextField filteredTextField;
    private javax.swing.JPanel filteredTextFieldPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList jlistHelper1;
    private javax.swing.JList jlistHelper2;
    private javax.swing.JPanel jlistHelperPanel;
    private javax.swing.JSpinner tableFilterIndexSpinner;
    private javax.swing.JTextField tableFilterTextField;
    // End of variables declaration//GEN-END:variables
}
